# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "\\[$username@$hostname $directory\\]% "

# Inserts a blank line between shell prompts
add_newline = false

[username]
disabled = false
show_always = true
format = '$user'

[hostname]
disabled = false
ssh_only = false
format = '$ssh_symbol$hostname'

[directory]
format = '$path$read_only'
